import type { Material, Category, Season, Theme, AgeGroup } from './types'
import { normalizeQuery, normalizeText } from './utils'

export const materials: Material[] = [
  {
    id: 'bear-simple-1',
    title: 'リボンをつけたかわいいくまさん',
    description: '蝶ネクタイをつけて手をふっているかわいいくまさんのぬりえ。シンプルな線で小さなお子様も楽しめます。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['くま', '動物', 'リボン', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: ['好きな色でくまさんを塗ってオリジナルのぬいぐるみを作ろう', '塗ったあとに名前をつけて発表ごっこをしよう'],
    imageUrl: '/materials/bear-simple-illust.png', illustUrl: '/materials/bear-simple-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'bear-easy-1',
    title: 'くまさんとはちみつ',
    description: 'かわいいくまさんとはちみつのつぼ、ハチさんが登場するほっこりぬりえです。',
    ageMin: 3, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['くま', 'はちみつ', 'ハチ', '動物', 'かわいい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: ['茶色や黄色を使ってくまさんとはちみつを塗ってみよう', '塗り終わったら「くまさんは何を食べているのかな?」とお話を広げよう'],
    imageUrl: '/materials/bear-easy-illust.png', illustUrl: '/materials/bear-easy-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'bear-normal-1',
    title: 'くまさんのピクニック',
    description: 'かわいいくまさんがサンドイッチやおにぎりを楽しむピクニックのぬりえです。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['くま', 'ピクニック', '動物', '食べ物', 'おにぎり', 'ちょうちょ'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: ['ぬりえの後、実際にお弁当を作ってピクニックごっこをしてみよう', 'くまさんが食べている食べ物の名前を一緒に言ってみよう'],
    imageUrl: '/materials/bear-normal-illust.png', illustUrl: '/materials/bear-normal-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'bear-rich-1',
    title: 'くまさんたちの公園あそび',
    description: 'くまの仲間たちが公園で滑り台や砂遊び、池で楽しく遊ぶにぎやかなぬりえです。',
    ageMin: 4, ageMax: 6, difficulty: 2, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['くま', '公園', '動物', 'あそび', '夏'],
    season: 'summer',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: ['それぞれのくまに名前と性格をつけてお話を作ってみよう', '自分が公園で遊んだ思い出の色を使って塗ってみよう'],
    imageUrl: '/materials/bear-rich-illust.png', illustUrl: '/materials/bear-rich-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'cat-simple',
    title: 'リボンをつけたねこちゃん',
    description: 'リボンをつけて手をふる、かわいい子猫のぬりえ。シンプルな線で小さなお子様にぴったり。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['ねこ', '動物', 'かわいい', 'リボン', '簡単'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: ['好きな色でねこちゃんを自由に塗ってみよう', 'リボンの色を考えて塗り、おしゃれなねこちゃんを作ろう'],
    imageUrl: '/materials/cat-simple-illust.png', illustUrl: '/materials/cat-simple-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'cat-easy',
    title: 'ねこときんぎょばち',
    description: 'リボンをつけたかわいいねこと、きんぎょばちのきんぎょをぬるぬりえです。',
    ageMin: 3, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['ねこ', 'きんぎょ', '動物', 'かわいい', 'リボン'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: ['ねこの毛色を自由に塗って、自分だけのねこを作ろう', 'きんぎょばちの水を青く塗って、お魚さんの色も考えてみよう'],
    imageUrl: '/materials/cat-easy-illust.png', illustUrl: '/materials/cat-easy-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'cat-normal',
    title: 'ねこちゃんとおさかなとミルク',
    description: 'リボンをつけたねこちゃんが、おさかなやミルク、毛糸玉と一緒にいるぬりえです。',
    ageMin: 3, ageMax: 4, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['ねこ', '動物', 'かわいい', 'おさかな', 'ミルク', '毛糸'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: ['ねこの鳴き声を真似しながら楽しく塗ってみよう', 'ねこが好きな食べ物について話し合いながら塗ろう'],
    imageUrl: '/materials/cat-normal-illust.png', illustUrl: '/materials/cat-normal-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'cat-rich',
    title: 'ねこたちの公園あそび',
    description: 'すべり台や砂遊び、魚釣りを楽しむかわいい子猫たちの賑やかな公園シーンのぬりえです。',
    ageMin: 4, ageMax: 6, difficulty: 2, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['ねこ', '公園', 'すべり台', '砂遊び', '夏', '動物'],
    season: 'summer',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: ['猫それぞれに違う毛色を塗って個性を出してみよう', '塗り終わった後にどの猫が何をしているかお話を作ってみよう'],
    imageUrl: '/materials/cat-rich-illust.png', illustUrl: '/materials/cat-rich-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'dog-simple',
    title: 'おすわりかわいいこいぬ',
    description: '首輪をつけたかわいい子犬がおすわりしているシンプルなぬりえ。小さなお子様にぴったりです。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['いぬ', 'こいぬ', 'どうぶつ', 'かわいい', 'ペット'],
    tools: ['クレヨン'],
    activityIdeas: [
      '茶色や白など好きな色で子犬を塗ってみよう',
      '首輪を好きな色にカラフルに塗って自分だけの子犬を作ろう',
    ],
    imageUrl: '/materials/dog-simple-illust.png', illustUrl: '/materials/dog-simple-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'dog-normal',
    title: 'いぬとおうち',
    description: 'かわいい子犬と犬小屋、お日さまや蝶々が描かれた楽しいぬりえです。',
    ageMin: 3, ageMax: 4, difficulty: 1, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['いぬ', '動物', '犬小屋', 'ちょうちょ', 'おひさま'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '色を塗りながら犬の鳴き声を真似してみよう',
      '自分のペットや好きな動物について話してみよう',
    ],
    imageUrl: '/materials/dog-normal-illust.png', illustUrl: '/materials/dog-normal-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'dog-rich',
    title: 'わんちゃんいっぱい！たのしいこうえん',
    description: 'たくさんの可愛い子犬たちが公園で遊ぶ賑やかなぬりえ。風車や虹、滑り台など細かい要素が満載です。',
    ageMin: 4, ageMax: 6, difficulty: 3, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['いぬ', 'こうえん', 'どうぶつ', 'あそび', 'にじ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '好きな子犬を選んで名前をつけてみよう',
      '虹の色を順番通りに塗って色の勉強をしよう',
    ],
    imageUrl: '/materials/dog-rich-illust.png', illustUrl: '/materials/dog-rich-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'rabbit-simple-1',
    title: 'かわいいうさぎさん',
    description: 'おすわりしているかわいい赤ちゃんうさぎのぬりえ。大きな耳とぷっくりした手足が魅力的です。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['うさぎ', '動物', 'かわいい', 'シンプル', '赤ちゃん'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'うさぎの好きな食べ物について話しながら塗ってみよう',
      'ピンクや白などお気に入りの色でうさぎさんを自由に塗ってみよう',
    ],
    imageUrl: '/materials/rabbit-simple-illust.png', illustUrl: '/materials/rabbit-simple-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'rabbit-easy-1',
    title: 'うさぎとにんじんとイースターバスケット',
    description: 'にんじんを抱えたかわいいうさぎとイースターエッグの入ったかごのぬりえです。',
    ageMin: 3, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['うさぎ', 'にんじん', 'イースター', '動物', 'かご'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'うさぎの体の色を自由に塗って、オリジナルのうさぎを作ってみよう',
      'イースターエッグに好きな模様を描き足してデコレーションしよう',
    ],
    imageUrl: '/materials/rabbit-easy-illust.png', illustUrl: '/materials/rabbit-easy-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'rabbit-normal-1',
    title: 'にんじんを持つうさぎとイースター',
    description: 'リボンをつけたうさぎがにんじんを持ち、卵やお花に囲まれた春らしいぬりえです。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['うさぎ', 'にんじん', 'イースター', 'たまご', 'ちょうちょ', 'チューリップ', '春'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'うさぎの好きな食べ物についてお話ししてみよう',
      'イースターエッグに自由な模様を描いてオリジナルの卵を作ろう',
    ],
    imageUrl: '/materials/rabbit-normal-illust.png', illustUrl: '/materials/rabbit-normal-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'rabbit-rich-1',
    title: 'うさぎたちの楽しい公園あそび',
    description: 'うさぎたちが池でボートに乗ったり、すべり台で遊んだりする賑やかな公園の風景です。',
    ageMin: 4, ageMax: 6, difficulty: 2, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['うさぎ', '公園', 'ボート', 'すべり台', 'お花', '動物'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'うさぎごとに違う色を使って塗り分けてみよう',
      '塗り終わったら、うさぎたちのお話を考えて発表しよう',
    ],
    imageUrl: '/materials/rabbit-rich-illust.png', illustUrl: '/materials/rabbit-rich-illust.png',
    illustVersion: 1, imageStatus: 'approved', pdfUrl: '', createdAt: '2026-05-08', popular: false,
  },
  {
    id: 'elephant-rich-1',
    title: 'ぞうさんたちのたのしいもりあそび',
    description: '4ひきのぞうさんがおひさま・きのみ・ちょうちょと一緒に元気よく遊ぶ、にぎやかなぬりえです。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ぞう', 'どうぶつ', 'ぬりえ', 'おひさま', 'おはな', 'ちょうちょ'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ぞうさんの体を何色にするか自由に考えて塗ってみる',
      '塗り終わったらぞうさんの名前を考えて発表する',
      'ぞうの鳴き声や動きをまねっこする遊びにつなげる',
      '動物園に行ったときの思い出を話し合う',
    ],
    imageUrl: '/materials/elephant-rich-1-illust.png',
    illustUrl: '/materials/elephant-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-08',
    popular: false,
  },
  {
    id: 'elephant-normal-1',
    title: 'きのしたのぞうさんとちょうちょ',
    description: '笑顔のぞうさんが木のそばでちょうちょやお花と一緒にたたずむ、春らしいぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ぞう', '動物', 'ぬりえ', 'ちょうちょ', 'お花'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ぞうさんは何色かな？想像して自由に色を塗ってみよう',
      'お花や蝶々もカラフルに塗って、にぎやかな景色にしよう',
      '塗り終わった作品を壁に飾って動物園ごっこを楽しむ',
      'ぞうの鳴き声や歩き方を真似しながら歌遊びにつなげる',
    ],
    imageUrl: '/materials/elephant-normal-1-illust.png',
    illustUrl: '/materials/elephant-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-08',
    popular: false,
  },
  {
    id: 'elephant-easy-1',
    title: 'ぞうさんとおはなのぬりえ',
    description: 'かわいい子ぞうとお花の線画ぬりえ。シンプルな線で小さなお子さまも塗りやすい一枚です。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ぞう', '動物', 'お花', 'ぬりえ', 'どうぶつ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ぞうさんを好きな色で自由に塗ってみよう',
      'ぞうさんの鳴き声を真似しながら塗って動物への興味を広げる',
      'お花の色を工夫して、季節のお花に変身させてみよう',
      '完成した絵を壁に飾って『ぞうさんのおはなばたけ』を作ろう',
    ],
    imageUrl: '/materials/elephant-easy-1-illust.png',
    illustUrl: '/materials/elephant-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-08',
    popular: false,
  },
  {
    id: 'elephant-simple-1',
    title: 'てをふるかわいいこぞうさん',
    description: '大きな耳と長い鼻をもつこぞうさんが、にっこり笑って手をふっているシンプルなぬりえです。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ぞう', 'どうぶつ', 'ぬりえ', 'シンプル'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ぞうさんを好きな色で塗ってみよう',
      '塗ったあとに動物園ごっこを楽しむ',
      'ぞうの鳴き声や歩き方をまねしてみる',
      '他の動物のぬりえと組み合わせて図鑑作り',
    ],
    imageUrl: '/materials/elephant-simple-1-illust.png',
    illustUrl: '/materials/elephant-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-08',
    popular: false,
  },
  {
    id: 'giraffe-rich-1',
    title: 'きりんのおやこと小鳥とおひさま',
    description: 'きりんの親子が草原で楽しく過ごすぬりえ。木や太陽、小鳥も登場するにぎやかな一枚です。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['きりん', '動物', '親子', 'サバンナ', 'ぬりえ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'きりんの模様を黄色や茶色で塗り分けて観察力を養う',
      '親子のきりんに名前をつけて物語を作って発表する',
      '塗り終わった作品を壁に貼ってサバンナの世界を再現する',
      '動物園の写真や図鑑と見比べて本物の色を調べてみる',
    ],
    imageUrl: '/materials/giraffe-rich-1-illust.png',
    illustUrl: '/materials/giraffe-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'giraffe-normal-1',
    title: 'きりんとおはなとしろいくも',
    description: 'かわいいキリンとお花や雲を自由に色付けできるぬりえ。動物が好きな子どもにぴったりです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['きりん', '動物', 'ぬりえ', 'お花', '雲'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'キリンの模様を好きな色で塗ってオリジナルのキリンを作る',
      '塗り終わった作品を壁に飾って動物園ごっこを楽しむ',
      'キリンの特徴（首が長い・模様がある）を話し合いながら塗る',
      '他の動物の絵と組み合わせてサバンナの世界を作る',
    ],
    imageUrl: '/materials/giraffe-normal-1-illust.png',
    illustUrl: '/materials/giraffe-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'giraffe-easy-1',
    title: 'あかちゃんキリンのぬりえ',
    description: 'おすわりするかわいい赤ちゃんキリンと葉っぱのぬりえ。大きな模様で塗りやすい線画です。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['キリン', '動物', '赤ちゃん動物', '葉っぱ', 'ぬりえ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'キリンの模様を好きな色で自由に塗ってみよう',
      '塗り終わったら動物園ごっこで他の動物と一緒に飾る',
      'キリンの首はなぜ長いのかお話ししながら塗る',
      '葉っぱを緑系のグラデーションで塗る練習をする',
    ],
    imageUrl: '/materials/giraffe-easy-1-illust.png',
    illustUrl: '/materials/giraffe-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'giraffe-simple-1',
    title: 'もようがたくさんきりんさん',
    description: '首の長いかわいいきりんのぬりえ。模様の丸を一つずつ塗って楽しめます。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['きりん', '動物', 'ぬりえ', 'サバンナ', 'どうぶつえん'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '黄色やオレンジを使って、きりんの体と模様を塗り分けてみよう',
      '塗り終わったら切り取ってサバンナの背景画用紙に貼り、世界に一つの動物園を作る',
      '『首の長い動物だね』と話しながら、他の動物の高さ比べゲームにつなげる',
      '模様の丸の数を数えて、数の学習にも活用する',
    ],
    imageUrl: '/materials/giraffe-simple-1-illust.png',
    illustUrl: '/materials/giraffe-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'lion-rich-1',
    title: 'ライオンかぞくのぬりえ',
    description: '草原で仲良く過ごすライオンの家族をぬりえで楽しめる、動物好きの子どもにぴったりの教材です。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ライオン', '動物', '家族', '草原', 'サバンナ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ライオンの家族構成について話し合いながら色を塗る',
      '塗り終わった作品を切り抜いて動物園ごっこを楽しむ',
      '親子ライオンの毛の色を変えて個性的に塗る',
      '背景の空や草を塗って物語を作って発表する',
    ],
    imageUrl: '/materials/lion-rich-1-illust.png',
    illustUrl: '/materials/lion-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'lion-normal-1',
    title: 'ライオンとおはなとおひさまのひ',
    description: '笑顔のかわいいライオンとお花や太陽を塗って楽しむぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ライオン', '動物', 'ぬりえ', 'お花', '太陽'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'たてがみの色を工夫して、自分だけのオリジナルライオンを作ろう',
      'ぬりえの後にライオンの鳴き声まねっこ遊びをする',
      '動物園ごっこにつなげて、他の動物のぬりえも集めて図鑑を作る',
      'お花や葉っぱの色も自由に塗って季節感を表現してみる',
    ],
    imageUrl: '/materials/lion-normal-1-illust.png',
    illustUrl: '/materials/lion-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'lion-easy-1',
    title: 'ライオンとおはなのぬりえ',
    description: 'にっこり笑顔のかわいいライオンとおはなをぬる、やさしいぬりえです。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ライオン', 'どうぶつ', 'おはな', 'ぬりえ', 'かわいい'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ライオンのたてがみを好きな色でカラフルにぬってみよう',
      '『ライオンは何を食べるかな？』と話しながら色を選ぶ',
      'ぬりえを切り取って画用紙に貼り、サバンナの世界を作る',
      'おはなの色をみんなで見せ合って発表会をする',
    ],
    imageUrl: '/materials/lion-easy-1-illust.png',
    illustUrl: '/materials/lion-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'lion-simple-1',
    title: 'たてがみふさふさらいおんさん',
    description: 'かわいいライオンの線画ぬりえ。たてがみや顔をカラフルにぬって楽しめます。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['どうぶつ', 'ライオン', 'ぬりえ', 'やさしい'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'たてがみを好きな色でカラフルにぬってみよう',
      'ぬり終わったら切り取って動物園マップを作る',
      '『ライオンの鳴き声は？』と動物クイズを楽しむ',
      '同じ動物の仲間を子どもたちと話し合う',
    ],
    imageUrl: '/materials/lion-simple-1-illust.png',
    illustUrl: '/materials/lion-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'panda-rich-1',
    title: 'パンダのかぞくのぬりえ',
    description: '竹やぶで遊ぶ3匹のかわいいパンダのぬりえ。太陽や雲も塗って楽しめます。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['パンダ', '動物', '竹', 'ぬりえ', '太陽'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '白黒のパンダの特徴を話し合いながら塗る',
      '竹の緑色を観察してから塗ってみる',
      '3匹のパンダに名前をつけてお話を作る',
      '塗り終わったら教室に飾ってパンダ動物園を作る',
    ],
    imageUrl: '/materials/panda-rich-1-illust.png',
    illustUrl: '/materials/panda-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'panda-normal-1',
    title: 'てをふるパンダと笹とおはな',
    description: '笹とお花と一緒に元気に手を振るかわいいパンダのぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['パンダ', '動物', '笹', 'お花', '太陽', 'ぬりえ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '白と黒のパンダの模様を観察してから色を塗ってみよう',
      '笹の葉や花を自由な色で塗ってオリジナルパンダを作ろう',
      '塗り終えたらパンダの名前を考えて発表ごっこをしよう',
      '動物園で見たパンダの思い出を話しながら塗ろう',
    ],
    imageUrl: '/materials/panda-normal-1-illust.png',
    illustUrl: '/materials/panda-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'panda-easy-1',
    title: '笹のそばにすわるかわいいパンダ',
    description: '笹と一緒に座る可愛いパンダの線画。シンプルな線で小さなお子様も塗りやすいぬりえです。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['パンダ', '動物', '笹', 'ぬりえ', 'かわいい'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '白と黒のパンダ模様を観察してから塗ってみよう',
      '笹の葉を緑色で塗って自然な雰囲気に仕上げる',
      '動物園で見たパンダの思い出を話しながら塗る',
      '完成後にパンダの好きな食べ物クイズで盛り上がる',
    ],
    imageUrl: '/materials/panda-easy-1-illust.png',
    illustUrl: '/materials/panda-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'panda-simple-1',
    title: 'てをふってえがおのパンダさん',
    description: '手をふって笑顔のかわいいパンダのぬりえ。シンプルな線で小さなお子様も楽しく色塗りができます。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['パンダ', '動物', 'ぬりえ', 'かわいい'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '白と黒だけでなく自由な色で塗ってオリジナルパンダを作ろう',
      'パンダの好きな食べ物（笹）を周りに描き足そう',
      '完成したぬりえを切り抜いて動物園ごっこを楽しもう',
      'お友だちと作品を見せ合って感想を伝え合おう',
    ],
    imageUrl: '/materials/panda-simple-1-illust.png',
    illustUrl: '/materials/panda-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-09',
    popular: false,
  },
  {
    id: 'penguin-rich-1',
    title: '氷の上であそぶ3びきのペンギン',
    description: '氷山と雪の結晶に囲まれて、氷の上で楽しそうに遊ぶペンギンたちと、ジャンプする魚を描いたぬりえ。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ペンギン', '冬', '雪', '氷', '動物', '魚'],
    season: 'winter',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ペンギンの白とお腹の部分を塗り分けて色の違いを楽しむ',
      '雪の結晶を青や水色で塗って冬の雰囲気を表現する',
      'ペンギンの生態について子どもたちと話しながら塗る',
      '塗り終わったら切り取って冬の壁面飾りにする',
    ],
    imageUrl: '/materials/penguin-rich-1-illust.png',
    illustUrl: '/materials/penguin-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'penguin-normal-1',
    title: 'ゆきとおさかなとごあいさつするペンギン',
    description: '手をあげたペンギンと雪の結晶、おさかな、氷が描かれた冬らしいぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ペンギン', '冬', '雪', '海の生き物', '氷'],
    season: 'winter',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ペンギンの体を黒、お腹を白く塗って本物そっくりに仕上げる',
      '雪の結晶を水色や銀色で塗って冬の世界を表現する',
      'ペンギンが住んでいる場所について子どもたちと話し合う',
      '塗り終わった作品を切り抜いて冬の壁面飾りにする',
    ],
    imageUrl: '/materials/penguin-normal-1-illust.png',
    illustUrl: '/materials/penguin-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'penguin-easy-1',
    title: 'ゆきのけっしょうにてをふるペンギン',
    description: '雪の結晶と一緒に手を振るかわいい子ペンギンのぬりえ。冬の季節感を楽しめる線画です。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ペンギン', '雪', '冬', '動物', 'ぬりえ'],
    season: 'winter',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '黒と白だけでなく青や水色も使ってペンギンらしく塗ってみる',
      '雪の結晶に銀色や水色を塗って氷の世界を表現する',
      '塗ったあと周りに自分で雪を描き足して冬の風景に仕上げる',
      'ペンギンの暮らす南極について絵本で学んでから取り組む',
    ],
    imageUrl: '/materials/penguin-easy-1-illust.png',
    illustUrl: '/materials/penguin-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'penguin-simple-1',
    title: 'てをふってあいさつするペンギン',
    description: '片方の羽を上げて元気にあいさつする、まんまるおなかのかわいいペンギンの線画です。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ペンギン', '動物', '鳥', '海の生き物', 'あいさつ'],
    season: 'winter',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '白と黒だけでなく、自由な色でカラフルなペンギンを塗ってみよう',
      'ペンギンの背景に氷山や海を描き足して南極の世界を作ろう',
      '塗り終わったペンギンを切り取って、お友達のペンギンと並べて飾ろう',
      'ペンギンの鳴き真似や歩き方を真似してリトミック遊びにつなげよう',
    ],
    imageUrl: '/materials/penguin-simple-1-illust.png',
    illustUrl: '/materials/penguin-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'sheep-rich-1',
    title: 'おはなばたけであそぶ5ひきのひつじ',
    description: 'お花畑と柵のある牧場で、5匹の羊たちがのんびり過ごす様子を描いたぬりえです。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひつじ', '牧場', 'お花', '動物', 'ぬりえ'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ひつじを数えながら塗って数の練習をする',
      'ふわふわの毛をわたで貼って立体的に仕上げる',
      'それぞれのひつじに名前をつけて物語を作る',
      'お花を好きな色で塗ってカラフルな牧場にする',
    ],
    imageUrl: '/materials/sheep-rich-1-illust.png',
    illustUrl: '/materials/sheep-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'sheep-normal-1',
    title: 'おはなばたけをジャンプするひつじさん',
    description: 'ふわふわのひつじが花畑を元気にジャンプしている、やさしい線画のぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひつじ', '動物', 'お花', '雲', '草原', 'ジャンプ'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ひつじのもこもこ部分を白く残して背景だけ塗る工夫を体験する',
      '綿を貼り付けてふわふわのひつじに仕上げる工作に発展させる',
      '『メリーさんのひつじ』を歌いながら塗って音楽と組み合わせる',
      '動物園や牧場で見たひつじの思い出を話しながら色を選ぶ',
    ],
    imageUrl: '/materials/sheep-normal-1-illust.png',
    illustUrl: '/materials/sheep-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'sheep-easy-1',
    title: 'おはなの横でジャンプするひつじさん',
    description: 'ふわふわの体で元気に飛び跳ねるひつじさんと、お花が描かれたぬりえです。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひつじ', '動物', 'お花', 'ジャンプ', 'ぬりえ'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ひつじの体をふわふわに見えるよう白やうすいピンクで塗ってみよう',
      '綿を貼り付けてふわふわの毛を表現する工作にアレンジ',
      '「メリーさんのひつじ」を歌いながら塗る活動',
      'お花の色を自由に決めて、自分だけのお花畑を完成させよう',
    ],
    imageUrl: '/materials/sheep-easy-1-illust.png',
    illustUrl: '/materials/sheep-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'sheep-simple-1',
    title: 'ぴょんとジャンプするひつじさん',
    description: '手を上げて元気にジャンプするふわふわひつじさんのぬりえ。やさしい線で塗りやすい一枚です。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひつじ', '動物', 'ぬりえ', 'ジャンプ', 'ふわふわ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '綿を貼り付けてふわふわのひつじさんを作る',
      'ひつじさんの毛の部分をぐるぐる模様で塗ってみる',
      'みんなでひつじになりきってジャンプ遊びをする',
    ],
    imageUrl: '/materials/sheep-simple-1-illust.png',
    illustUrl: '/materials/sheep-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'pig-rich-1',
    title: 'ぼくじょうであそぶこぶたたち',
    description: '牧場の小屋や木のそばで、4匹のこぶたが楽しそうに過ごしているぬりえです。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['こぶた', 'ぶた', '牧場', '動物', '小屋', 'お花'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'こぶたごとに違う色を塗って、家族や仲間に見立ててみる',
      '牧場にいる他の動物を描き足してオリジナル牧場を作る',
      'ぶたの鳴き声をまねっこして動物の声あそびをする',
      '「3びきのこぶた」の絵本を読んでからぬりえに取り組む',
    ],
    imageUrl: '/materials/pig-rich-1-illust.png',
    illustUrl: '/materials/pig-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'pig-normal-1',
    title: 'みずたまりでジャンプするこぶたとちょうちょ',
    description: '水たまりで元気にジャンプするこぶたと、ちょうちょやお花が描かれた春らしいぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['こぶた', 'ちょうちょ', 'お花', '水たまり', '動物'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'こぶたの体をピンク色に塗って、ほっぺをもっと赤くしてみよう',
      'ちょうちょの羽を好きな模様や色で自由にデザインしよう',
      '水たまりに自分の好きな色を塗って、季節を表現してみよう',
      '塗り終わったら背景に空や草を描き足してオリジナル作品にしよう',
    ],
    imageUrl: '/materials/pig-normal-1-illust.png',
    illustUrl: '/materials/pig-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'pig-easy-1',
    title: 'おはなにむかってかけるこぶた',
    description: '元気に走るこぶたと、そのそばに咲く一輪の花を描いたぬりえ。シンプルな線で小さなお子さまにもぴったり。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['こぶた', 'ぶた', 'お花', '動物', 'ぬりえ', 'かわいい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ピンクや好きな色でこぶたを塗ってみよう',
      'お花の花びらを一枚ずつ違う色で塗ってカラフルにしよう',
      '塗り終わったら『ぶたさんはどこへ走っているのかな?』とお話を作って遊ぼう',
      '背景に草や空を描き足してオリジナルの絵に仕上げよう',
    ],
    imageUrl: '/materials/pig-easy-1-illust.png',
    illustUrl: '/materials/pig-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'pig-simple-1',
    title: 'おててをふってあるくこぶたさん',
    description: '片手をあげて элегントにあいさつしながら歩く、笑顔のこぶたのぬりえです。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['こぶた', '動物', 'ぬりえ', '笑顔', 'あいさつ'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ピンク色を使ってこぶたさんを塗ってみよう',
      '塗り終わったら『こぶたさん、こんにちは』とごあいさつごっこ',
      '好きな色でカラフルなこぶたさんに変身させてみる',
      '切り取って画用紙に貼り、お散歩風景を作ろう',
    ],
    imageUrl: '/materials/pig-simple-1-illust.png',
    illustUrl: '/materials/pig-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'frog-rich-1',
    title: 'にじのいけでジャンプするカエルたち',
    description: '虹のかかる池で、はすの葉に乗ったカエルたちが楽しそうにジャンプしたり手を振ったりしているぬりえです。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['カエル', '池', '虹', 'はすの葉', '梅雨', '雨上がり'],
    season: 'summer',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '虹を七色に塗り分けて色の名前を覚える',
      'カエルの鳴き声をまねしながらぬりえを楽しむ',
      'ぬりえを切り抜いて池の壁面飾りを作る',
      '梅雨の季節に歌『かえるのうた』と一緒に取り組む',
    ],
    imageUrl: '/materials/frog-rich-1-illust.png',
    illustUrl: '/materials/frog-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'frog-normal-1',
    title: 'はっぱのかさをさすカエルとちょうちょとはす',
    description: '葉っぱの傘をさしたカエルが、ちょうちょと蓮の花と一緒にいる、梅雨の季節にぴったりのぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['カエル', 'ちょうちょ', 'はす', '葉っぱ', '梅雨', 'ぬりえ'],
    season: 'summer',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '梅雨の季節に雨や水たまりを背景に描き足して仕上げる',
      'カエルの体の色を自由に想像して塗ってみる',
      'ちょうちょの羽の模様を左右対称に塗る練習をする',
      '塗り終わった作品を切り抜いて壁面装飾にする',
    ],
    imageUrl: '/materials/frog-normal-1-illust.png',
    illustUrl: '/materials/frog-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'frog-easy-1',
    title: 'はすのはにのるにこにこかえるさん',
    description: 'はすの葉の上でにっこり笑うかえるさんのぬりえ。大きな目と笑顔がかわいい線画です。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['かえる', 'はすのは', '池', '動物', 'ぬりえ'],
    season: 'summer',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '緑色のいろいろな濃淡を使ってかえるを塗り分けてみよう',
      'かえるの鳴き声『ケロケロ』を真似しながら塗ってみる',
      '塗り終わったら切り取って池の壁面飾りにする',
      '梅雨や夏の季節の制作活動として取り入れる',
    ],
    imageUrl: '/materials/frog-easy-1-illust.png',
    illustUrl: '/materials/frog-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'frog-simple-1',
    title: 'てをふるにこにこかえるさん',
    description: '立ち上がって手を振る笑顔のかえるさん。大きな目とまるいお腹がかわいい線画です。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['かえる', '動物', '笑顔', '梅雨', 'あいさつ'],
    season: 'summer',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '緑や黄緑など自由な色でかえるさんを塗ってみよう',
      'かえるの鳴き声を真似しながら塗ってみよう',
      '梅雨の季節に雨やあじさいの絵を周りに描き足そう',
    ],
    imageUrl: '/materials/frog-simple-1-illust.png',
    illustUrl: '/materials/frog-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'approved',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'monkey-rich-1',
    title: 'ジャングルでバナナをたべるおさるさんたち',
    description: '木の上やつるにぶら下がる5匹のおさるさんたちが、ジャングルでバナナを楽しむにぎやかなぬりえです。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['さる', 'ジャングル', 'バナナ', '動物', '木', 'ぬりえ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '茶色や黄色を使っておさるさんとバナナを塗り分ける練習をする',
      'ジャングルの植物を緑のグラデーションで表現してみる',
      '塗り終わったあと、おさるさんごとに名前を付けてお話を作る',
      '動物園や絵本のおさるさんを思い出しながら鳴き声まねを楽しむ',
    ],
    imageUrl: '/materials/monkey-rich-1-illust.png',
    illustUrl: '/materials/monkey-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'monkey-normal-1',
    title: 'バナナとボールであそぶこざるさん',
    description: '木の枝を持って笑うこざると、バナナ・葉っぱ・ボールが描かれたぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['さる', 'どうぶつ', 'バナナ', 'ボール', 'ジャングル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '茶色や黄色など暖色系の色使いを練習する',
      'ジャングルにすむ動物について話し合う',
      'ぬりえの後にバナナを実際に食べておやつタイムにする',
      'さるのまねっこ遊びをして体を動かす',
    ],
    imageUrl: '/materials/monkey-normal-1-illust.png',
    illustUrl: '/materials/monkey-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'monkey-easy-1',
    title: 'バナナにてをのばすおさるさん',
    description: 'おすわりしたおさるさんが、うれしそうにバナナへ手をのばしているぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['さる', 'バナナ', 'どうぶつ', 'くだもの', 'ぬりえ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '茶色や黄色など好きな色でおさるさんとバナナを塗ってみよう',
      'おさるさんの好きな食べ物について話し合ってみよう',
      'ぬりえのあとにジャングルの背景を描き足してみよう',
      '完成した作品でどうぶつえんごっこを楽しもう',
    ],
    imageUrl: '/materials/monkey-easy-1-illust.png',
    illustUrl: '/materials/monkey-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'monkey-simple-1',
    title: 'おててをふるこざるさん',
    description: 'くるんとしたしっぽがかわいい、おててをふって挨拶するこざるのぬりえです。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['さる', 'どうぶつ', 'ぬりえ', 'あいさつ'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '茶色や黄土色など、さるの色を観察してから塗ってみる',
      '塗り終わったらバナナや木を描き足してジャングルを作る',
      '「おはよう」「バイバイ」など挨拶ごっこをしながら塗る',
    ],
    imageUrl: '/materials/monkey-simple-1-illust.png',
    illustUrl: '/materials/monkey-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'chick-rich-1',
    title: 'おひさまの下であそぶひよこたち',
    description: 'おひさまの下、お庭で元気に遊ぶ5羽のひよこたち。エサをついばんだり巣で休んだりする、にぎやかな線画です。',
    ageMin: 3,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひよこ', '鳥', 'おひさま', 'お花', 'お庭', '春'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '黄色やオレンジなど色を変えて、ひよこごとに違う色で塗ってみよう',
      'ひよこの鳴き声をまねしながら塗って、表現遊びを楽しもう',
      '塗り終わったら『どのひよこが好き？』とみんなで発表会をしよう',
      '春の歌『ひよこ』を歌いながら塗り絵タイムにしよう',
    ],
    imageUrl: '/materials/chick-rich-1-illust.png',
    illustUrl: '/materials/chick-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'chick-normal-1',
    title: 'たまごからうまれたひよことちょうちょ',
    description: 'ひよこがたまごのからから飛び出し、ちょうちょやお花と春のよろこびをかんじるぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひよこ', 'たまご', 'ちょうちょ', 'お花', '春', '動物'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'ひよこの誕生をテーマにいのちのお話をする',
      'ぬりえ後にたまごの殻を画用紙で作って立体工作にする',
      '春の生きもの探しごっこに発展させる',
      'ちょうちょとひよこになりきってリズム遊びをする',
    ],
    imageUrl: '/materials/chick-normal-1-illust.png',
    illustUrl: '/materials/chick-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'chick-easy-1',
    title: 'たまごからうまれたひよこ',
    description: '割れたたまごのからからうまれたばかりのひよこが元気に歩き出すぬりえです。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひよこ', 'たまご', '動物', '春', '誕生'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '黄色のクレヨンでひよこをぬってみよう',
      'たまごのからに模様を描いてオリジナルにしよう',
      'ひよこの鳴き声をまねしながらぬり絵を楽しもう',
    ],
    imageUrl: '/materials/chick-easy-1-illust.png',
    illustUrl: '/materials/chick-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'chick-simple-1',
    title: 'あんよをあげておどるひよこ',
    description: '片足をあげて元気におどるひよこの線画。シンプルで塗りやすい構図です。',
    ageMin: 2,
    ageMax: 4,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ひよこ', 'とり', 'どうぶつ', 'かわいい', 'ぬりえ'],
    season: 'spring',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      '黄色いクレヨンで全体を塗ってかわいいひよこに仕上げる',
      'ひよこの鳴き声をまねしながら楽しく色塗りする',
      '塗り終わったら台紙に貼って、おはなばたけや巣の絵を描き足す',
      '春の制作として、たまごの殻と組み合わせて飾る',
    ],
    imageUrl: '/materials/chick-simple-1-illust.png',
    illustUrl: '/materials/chick-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'fox-rich-1',
    title: 'もりであそぶこぎつねたち',
    description: 'きのきりかぶやきのこ、おはなにかこまれた森で、4ひきのこぎつねが元気にあそぶ線画です。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 2,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['きつね', '森', '動物', '自然', 'ぬりえ'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'きつねごとに違う色を塗って家族のお話を作る',
      '背景の草花やきのこを好きな色で自由に塗る',
      '塗り終えた絵を壁に貼って森のジオラマ風に飾る',
      'きつねたちの名前や鳴き声を考えてごっこ遊びをする',
    ],
    imageUrl: '/materials/fox-rich-1-illust.png',
    illustUrl: '/materials/fox-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'fox-normal-1',
    title: 'きのこと落ち葉とこぎつね',
    description: '森を歩く子ぎつねと、きのこ・落ち葉が描かれた秋らしいぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['きつね', '森', 'きのこ', '落ち葉', '秋', '動物'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'オレンジや茶色を使って秋の色合いを楽しむ',
      'きつねがどこへ行くのかお話を作って発表する',
      '本物の落ち葉を集めて作品の周りに貼る',
      'きのこの模様を自由にアレンジして塗る',
    ],
    imageUrl: '/materials/fox-normal-1-illust.png',
    illustUrl: '/materials/fox-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'fox-easy-1',
    title: 'きのこをみつけたこぎつね',
    description: 'ふさふさのしっぽが可愛いこぎつねと小さなきのこの線画。秋の森を感じる優しい雰囲気のぬりえです。',
    ageMin: 3,
    ageMax: 5,
    difficulty: 1,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['きつね', 'どうぶつ', 'きのこ', '森', 'ぬりえ'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'オレンジや茶色を使ってきつねの毛並みを表現してみよう',
      'きのこの模様を自由にデザインしてオリジナルのきのこを作ろう',
      '周りに森の木や落ち葉を描き足して秋の風景を完成させよう',
      'きつねに名前をつけてお話を作ってみよう',
    ],
    imageUrl: '/materials/fox-easy-1-illust.png',
    illustUrl: '/materials/fox-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'fox-simple-1',
    title: 'ふわふわしっぽのこぎつね',
    description: 'ちょこんとお座りした子ぎつねが、大きなふわふわのしっぽを見せてにっこり笑っているぬりえです。',
    ageMin: 2,
    ageMax: 5,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['きつね', '動物', 'かわいい', 'シンプル', 'お座り'],
    tools: ['クレヨン', '色鉛筆', 'サインペン'],
    activityIdeas: [
      'オレンジや茶色などきつねらしい色を選んで塗ってみる',
      'しっぽの先だけ違う色にしてみるなど工夫して塗る',
      '塗り終わったら森の背景を描き足してオリジナル作品にする',
      '「コンコン」と鳴き声を真似しながらきつねごっこを楽しむ',
    ],
    imageUrl: '/materials/fox-simple-1-illust.png',
    illustUrl: '/materials/fox-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'raccoon-simple-1',
    title: 'てをふるたぬき',
    description: '1匹のたぬきが手をふっているシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['たぬき', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'たぬきの色を自由に塗ってオリジナルたぬきを作ろう',
      'たぬきのしっぽは何色にする？話し合ってみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/raccoon-simple-1-illust.png',
    illustUrl: '/materials/raccoon-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'raccoon-easy-1',
    title: 'どんぐりをもつたぬき',
    description: 'どんぐりを持ってすわるたぬきのぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['たぬき', 'どうぶつ', 'どんぐり', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'どんぐりは何色？茶色や黄色で塗ってみよう',
      'たぬきのおなかの模様に注目して塗ってみよう',
      'どんぐりを集めるたぬきのお話を作ってみよう',
    ],
    imageUrl: '/materials/raccoon-easy-1-illust.png',
    illustUrl: '/materials/raccoon-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'raccoon-normal-1',
    title: 'きのこときのはとたぬき',
    description: 'たぬきときのこ・木の葉・どんぐりが並ぶ秋らしいぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['たぬき', 'どうぶつ', 'きのこ', 'どんぐり', 'あき'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'きのこを赤や黄色など好きな色で塗ってみよう',
      '秋の色（茶色・橙・黄色）を使って塗ってみよう',
      'たぬきが何を集めているか話し合ってみよう',
      'どんぐりや木の葉を本物と見比べてみよう',
    ],
    imageUrl: '/materials/raccoon-normal-1-illust.png',
    illustUrl: '/materials/raccoon-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'raccoon-rich-1',
    title: 'もりのたぬきたちのしゅうかく',
    description: '森の中でたくさんのたぬきが木の実を集めるにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['たぬき', 'どうぶつ', 'もり', 'あき', 'にぎやか'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      'それぞれのたぬきを違う色で塗り分けよう',
      '背景の木や切り株も丁寧に色を塗ってみよう',
      'たぬきたちの名前を考えてお話を作ろう',
      '一番好きなたぬきはどれか、理由と一緒に発表しよう',
    ],
    imageUrl: '/materials/raccoon-rich-1-illust.png',
    illustUrl: '/materials/raccoon-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'squirrel-simple-1',
    title: 'てをふるりす',
    description: '1匹のりすが手をふっているシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['りす', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'りすの色を自由に塗ってオリジナルりすを作ろう',
      'しっぽはどんな色にする？話し合ってみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/squirrel-simple-1-illust.png',
    illustUrl: '/materials/squirrel-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'squirrel-easy-1',
    title: 'どんぐりをかかえるりす',
    description: '大きなどんぐりを両手で抱えるりすのぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['りす', 'どうぶつ', 'どんぐり', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'どんぐりは何色？茶色や黄色で塗ってみよう',
      'りすのふわふわしっぽを好きな色で塗ろう',
      'どんぐりを集めるりすのお話を作ってみよう',
    ],
    imageUrl: '/materials/squirrel-easy-1-illust.png',
    illustUrl: '/materials/squirrel-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'squirrel-normal-1',
    title: 'どんぐりときのことはっぱのりす',
    description: 'りすのそばにどんぐり・きのこ・葉っぱが並ぶ秋らしいぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['りす', 'どうぶつ', 'どんぐり', 'きのこ', 'あき'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'きのこを赤や黄色など好きな色で塗ってみよう',
      '秋の色（茶色・橙・黄色）を使って塗ってみよう',
      'りすが何を食べているか話し合ってみよう',
      'どんぐりや葉っぱを本物と見比べてみよう',
    ],
    imageUrl: '/materials/squirrel-normal-1-illust.png',
    illustUrl: '/materials/squirrel-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'squirrel-rich-1',
    title: 'もりのりすたちのどんぐりあつめ',
    description: '森の木や切り株・丸太の上で5匹のりすがどんぐりを集めるにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['りす', 'どうぶつ', 'もり', 'あき', 'にぎやか', 'どんぐり'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      'それぞれのりすを違う色で塗り分けよう',
      '背景の木や切り株も丁寧に色を塗ってみよう',
      'りすたちの名前を考えてお話を作ろう',
      '一番好きなりすはどれか、理由と一緒に発表しよう',
    ],
    imageUrl: '/materials/squirrel-rich-1-illust.png',
    illustUrl: '/materials/squirrel-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'turtle-simple-1',
    title: 'にっこりかめさん',
    description: '1匹のかめがにっこり笑うシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['かめ', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'かめのこうらを好きな色で塗ってみよう',
      'こうらの模様に注目して塗り分けてみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/turtle-simple-1-illust.png',
    illustUrl: '/materials/turtle-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'turtle-easy-1',
    title: 'およぐかめとヒトデ',
    description: 'およぐかめとかわいいヒトデのぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['かめ', 'どうぶつ', 'ヒトデ', 'うみ', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ヒトデは何色？オレンジや黄色で塗ってみよう',
      'かめのひれをどんな色にするか考えてみよう',
      'うみの中をおよぐかめのお話を作ってみよう',
    ],
    imageUrl: '/materials/turtle-easy-1-illust.png',
    illustUrl: '/materials/turtle-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'turtle-normal-1',
    title: 'かいそうとかいがらとヒトデのかめ',
    description: 'かめのそばに海藻・貝がら・ヒトデが並ぶ海らしいぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['かめ', 'どうぶつ', 'うみ', 'かいそう', 'かいがら', 'ヒトデ'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '海藻は緑色で塗ってみよう',
      '貝がらをピンクや白で塗ってみよう',
      '海の生き物の色を本物と比べてみよう',
      'かめが海でどんなことをしているか話し合ってみよう',
    ],
    imageUrl: '/materials/turtle-normal-1-illust.png',
    illustUrl: '/materials/turtle-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'turtle-rich-1',
    title: 'うみのなかのかめたちのせかい',
    description: '海の中で4匹のかめが泳ぎまわるにぎやかなぬりえ。島・サンゴ・ヒトデも登場。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['かめ', 'どうぶつ', 'うみ', 'サンゴ', 'にぎやか'],
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      'それぞれのかめを違う色で塗り分けよう',
      'サンゴや海藻も好きな色で塗ってみよう',
      'かめたちの名前を考えてお話を作ろう',
      '一番好きなかめはどれか、理由と一緒に発表しよう',
    ],
    imageUrl: '/materials/turtle-rich-1-illust.png',
    illustUrl: '/materials/turtle-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-10',
    popular: false,
  },
  {
    id: 'hamster-simple-1',
    title: 'まんまるハムスター',
    description: 'ハムスター1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ハムスター', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ハムスターの色を自由に塗ってオリジナルハムスターを作ろう',
      'ほっぺたがぷくぷくなのはなぜか話し合ってみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/hamster-simple-1-illust.png',
    illustUrl: '/materials/hamster-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hamster-easy-1',
    title: 'ホイールをはしるハムスター',
    description: 'ハムスターがホイールを元気に走っているぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ハムスター', 'どうぶつ', 'ホイール', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ホイールは何色に塗る？好きな色を選ぼう',
      'ハムスターはどのくらい速く走れるか調べてみよう',
      '走るハムスターのお話を作ってみよう',
    ],
    imageUrl: '/materials/hamster-easy-1-illust.png',
    illustUrl: '/materials/hamster-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hamster-normal-1',
    title: 'たねとどんぐりとおうちのハムスター',
    description: 'ハムスターのそばにひまわりの種・どんぐり・小屋が並ぶぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ハムスター', 'どうぶつ', 'どんぐり', 'たね', 'おうち'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ひまわりの種とどんぐりを塗り分けてみよう',
      'ハムスターの小屋をカラフルに塗ってみよう',
      'ハムスターはどんなものを食べるか話し合ってみよう',
      'ほっぺたに食べ物を詰めるハムスターのお話を作ろう',
    ],
    imageUrl: '/materials/hamster-normal-1-illust.png',
    illustUrl: '/materials/hamster-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hamster-rich-1',
    title: 'ハムスターたちのにぎやかなへや',
    description: '小屋・ホイール・ハンモック・トンネルのある部屋で6匹のハムスターが遊ぶにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ハムスター', 'どうぶつ', 'にぎやか', 'おうち', 'ホイール'],
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      'それぞれのハムスターを違う色で塗り分けよう',
      '小屋やホイールも好きな色で塗ってみよう',
      'ハムスターたちの名前を考えてお話を作ろう',
      '一番好きなハムスターはどれか、理由と一緒に発表しよう',
    ],
    imageUrl: '/materials/hamster-rich-1-illust.png',
    illustUrl: '/materials/hamster-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'bird-simple-1',
    title: 'にっこりことり',
    description: 'ことり1羽のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ことり', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ことりを好きな色で塗ってオリジナルことりを作ろう',
      'どんな鳴き声か真似してみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/bird-simple-1-illust.png',
    illustUrl: '/materials/bird-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'bird-easy-1',
    title: 'えだにとまることり',
    description: 'ことり1羽が枝にとまって歌っているぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['ことり', 'どうぶつ', 'えだ', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ことりの羽を好きな色で塗ってみよう',
      '枝はどんな色？茶色で塗ってみよう',
      'ことりが歌っている歌を考えてみよう',
    ],
    imageUrl: '/materials/bird-easy-1-illust.png',
    illustUrl: '/materials/bird-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'bird-normal-1',
    title: 'すとはなとことり',
    description: 'ことりのそばに巣・花・葉っぱが並ぶぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['ことり', 'どうぶつ', 'す', 'はな', 'はっぱ'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '花を好きな色で塗ってみよう',
      '巣はどんな色や形か観察しながら塗ってみよう',
      'ことりが巣を作るお話を作ってみよう',
      '葉っぱを緑のいろいろな色で塗り分けてみよう',
    ],
    imageUrl: '/materials/bird-normal-1-illust.png',
    illustUrl: '/materials/bird-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'bird-rich-1',
    title: 'きのうえでうたうことりたち',
    description: '木の上で歌ったり飛んだりする8羽のことりと巣・巣箱のにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['ことり', 'どうぶつ', 'き', 'うた', 'にぎやか'],
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      'それぞれのことりを違う色で塗り分けよう',
      '木の葉や空も丁寧に塗ってみよう',
      'ことりたちの名前を考えてお話を作ろう',
      '一番好きなことりはどれか、理由と一緒に発表しよう',
    ],
    imageUrl: '/materials/bird-rich-1-illust.png',
    illustUrl: '/materials/bird-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'boar-simple-1',
    title: 'にっこりいのしし',
    description: 'いのしし1頭のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['いのしし', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'いのししを好きな色で塗ってみよう',
      'きばに注目してみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/boar-simple-1-illust.png',
    illustUrl: '/materials/boar-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'boar-easy-1',
    title: 'どんぐりをかじるいのしし',
    description: 'いのししがどんぐりをかじっているぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['いのしし', 'どうぶつ', 'どんぐり', 'やさしい'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'どんぐりは何色？茶色や黄色で塗ってみよう',
      'いのししのしま模様を塗り分けてみよう',
      'いのししが森で何を食べているか話し合ってみよう',
    ],
    imageUrl: '/materials/boar-easy-1-illust.png',
    illustUrl: '/materials/boar-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'boar-normal-1',
    title: 'どんぐりときのことはっぱのいのしし',
    description: 'いのししのそばにどんぐり・きのこ・葉っぱが並ぶ秋らしいぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['いのしし', 'どうぶつ', 'どんぐり', 'きのこ', 'あき'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'きのこを赤や黄色など好きな色で塗ってみよう',
      '秋の色（茶色・橙・黄色）を使って塗ってみよう',
      'いのししが森でどんなことをしているか話し合ってみよう',
      'どんぐりや葉っぱを本物と見比べてみよう',
    ],
    imageUrl: '/materials/boar-normal-1-illust.png',
    illustUrl: '/materials/boar-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'boar-rich-1',
    title: 'もりをはしるいのししおやこ',
    description: '親いのししと3匹の子いのししが森を元気に走るにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['いのしし', 'どうぶつ', 'もり', 'あき', 'にぎやか', 'おやこ'],
    season: 'autumn',
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      '親と子いのししを塗り分けてみよう',
      '背景の木や草も丁寧に塗ってみよう',
      'いのしし家族のお話を作ろう',
      '一番好きないのししはどれか、理由と一緒に発表しよう',
    ],
    imageUrl: '/materials/boar-rich-1-illust.png',
    illustUrl: '/materials/boar-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'horse-simple-1',
    title: 'にっこりこうま',
    description: 'こうま1頭のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['こうま', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'こうまを好きな色で塗ってみよう',
      'たてがみを何色にするか考えてみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/horse-simple-1-illust.png',
    illustUrl: '/materials/horse-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'horse-easy-1',
    title: 'はなばたけのこうま',
    description: 'こうまが花畑の草原を歩いているぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['こうま', 'どうぶつ', 'はな', 'くさはら', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      '花をカラフルに塗ってみよう',
      'こうまのたてがみをふわふわに塗ってみよう',
      'こうまがどこへ向かっているかお話を作ってみよう',
    ],
    imageUrl: '/materials/horse-easy-1-illust.png',
    illustUrl: '/materials/horse-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'horse-normal-1',
    title: 'ちょうちょとはなとこうま',
    description: 'こうまのそばに花・草・ちょうちょが並ぶぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['こうま', 'どうぶつ', 'はな', 'ちょうちょ', 'くさはら'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ちょうちょを好きな色で塗ってみよう',
      '花を何色にするか考えて塗り分けてみよう',
      'こうまとちょうちょが友達になるお話を作ってみよう',
      '草原の緑をいろいろな緑で塗り分けてみよう',
    ],
    imageUrl: '/materials/horse-normal-1-illust.png',
    illustUrl: '/materials/horse-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'horse-rich-1',
    title: 'おやこのこうまがはなばたけをかける',
    description: '親子のこうまが花畑をちょうちょと一緒に走るにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['こうま', 'どうぶつ', 'おやこ', 'はな', 'にぎやか'],
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      '親と子こうまを違う色で塗り分けよう',
      '背景の花や木も丁寧に塗ってみよう',
      'こうま家族のお話を作ろう',
      'どのちょうちょが好きか選んで塗ってみよう',
    ],
    imageUrl: '/materials/horse-rich-1-illust.png',
    illustUrl: '/materials/horse-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'koala-simple-1',
    title: 'てをふるこあら',
    description: 'こあら1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['こあら', 'どうぶつ', 'かんたん', 'シンプル'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'こあらを好きな色で塗ってみよう',
      'ふわふわの耳に注目して塗ってみよう',
      '塗った後に好きな名前をつけてあげよう',
    ],
    imageUrl: '/materials/koala-simple-1-illust.png',
    illustUrl: '/materials/koala-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'koala-easy-1',
    title: 'えだでねむるこあら',
    description: 'こあらがユーカリの枝でうとうと眠っているぬりえ。3歳向けのやさしい構図。',
    ageMin: 3,
    ageMax: 3,
    difficulty: 1,
    duration: 10,
    category: 'coloring',
    theme: 'animals',
    tags: ['こあら', 'どうぶつ', 'ユーカリ', 'やさしい'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'こあらはどんな色？灰色や茶色で塗ってみよう',
      '木の幹を茶色で塗ってみよう',
      'こあらが何を夢見ているかお話を作ってみよう',
    ],
    imageUrl: '/materials/koala-easy-1-illust.png',
    illustUrl: '/materials/koala-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'koala-normal-1',
    title: 'ユーカリのはなとこあら',
    description: 'こあらのそばにユーカリの花・葉っぱ・星が並ぶぬりえ。3〜4歳向け。',
    ageMin: 3,
    ageMax: 4,
    difficulty: 2,
    duration: 15,
    category: 'coloring',
    theme: 'animals',
    tags: ['こあら', 'どうぶつ', 'ユーカリ', 'はな', 'ほし'],
    tools: ['クレヨン', '色鉛筆'],
    activityIdeas: [
      'ユーカリの花を好きな色で塗ってみよう',
      '星を黄色や金色で輝かせよう',
      'こあらとユーカリの関係について話し合ってみよう',
      '葉っぱをいろいろな緑で塗り分けてみよう',
    ],
    imageUrl: '/materials/koala-normal-1-illust.png',
    illustUrl: '/materials/koala-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'koala-rich-1',
    title: 'ユーカリのきでだっこするおやこあら',
    description: '親こあらが赤ちゃんをだっこしてユーカリの木にいるにぎやかなぬりえ。4〜6歳向け。',
    ageMin: 4,
    ageMax: 6,
    difficulty: 3,
    duration: 20,
    category: 'coloring',
    theme: 'animals',
    tags: ['こあら', 'どうぶつ', 'おやこ', 'ユーカリ', 'にぎやか'],
    tools: ['クレヨン', '色鉛筆', '水彩'],
    activityIdeas: [
      '親と子こあらを塗り分けてみよう',
      '背景の木や空も丁寧に塗ってみよう',
      'こあら家族のお話を作ろう',
      'ことりを見つけて色を塗ってみよう',
    ],
    imageUrl: '/materials/koala-rich-1-illust.png',
    illustUrl: '/materials/koala-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'whale-simple-1',
    title: 'かわいいくじらさん',
    description: '正面を向いたかわいいくじらのぬりえ。大きな体と笑顔がかわいいよ。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['くじら', '海の動物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'くじらを好きな色でぬってみよう',
      'くじらはどんな海に住んでいるかな？',
    ],
    imageUrl: '/materials/whale-simple-1-illust.png',
    illustUrl: '/materials/whale-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'whale-easy-1',
    title: 'しおふきくじらさん',
    description: 'しおを吹き上げながら海を泳ぐくじらのぬりえ。波の上でダイナミックなしぐさが楽しいよ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['くじら', '海', 'しおふき', 'かわいい'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'しおをどんな色にする？',
      '波も青くぬってみよう',
    ],
    imageUrl: '/materials/whale-easy-1-illust.png',
    illustUrl: '/materials/whale-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'whale-normal-1',
    title: 'うみのなかのくじらさん',
    description: '海藻や小魚と一緒に泳ぐくじらのぬりえ。海の中の仲間たちも一緒にぬれるよ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['くじら', '海', '魚', '海藻'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '魚をいろんな色でぬってみよう',
      '海の中はどんな色かな？',
    ],
    imageUrl: '/materials/whale-normal-1-illust.png',
    illustUrl: '/materials/whale-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'whale-rich-1',
    title: 'くじらのおやこと海の仲間たち',
    description: 'くじらの親子がサンゴや魚たちと泳ぐ豊かな海のぬりえ。たくさんの生き物を楽しんでぬれるよ。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['くじら', '海', 'サンゴ', '親子', 'やりがい'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      'サンゴや海藻も色とりどりにぬってみよう',
      '海の生き物を全部見つけて数えてみよう',
    ],
    imageUrl: '/materials/whale-rich-1-illust.png',
    illustUrl: '/materials/whale-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'deer-simple-1',
    title: 'かわいいしかさん',
    description: '正面を向いたかわいいしかのぬりえ。大きな目とツノがチャーミングだよ。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['しか', '動物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'しかを好きな色でぬってみよう',
      'しかのツノは何本かな？数えてみよう',
    ],
    imageUrl: '/materials/deer-simple-1-illust.png',
    illustUrl: '/materials/deer-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'deer-easy-1',
    title: 'くさをたべるしかさん',
    description: '草原で草を食べているしかのぬりえ。シンプルな草むらの背景で楽しくぬれるよ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['しか', '動物', '草原', 'かわいい'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'しかのおなかの模様もぬってみよう',
      '草は何色にする？',
    ],
    imageUrl: '/materials/deer-easy-1-illust.png',
    illustUrl: '/materials/deer-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'deer-normal-1',
    title: 'もりのしかさんとことり',
    description: '木のそばを歩くしかと小鳥のぬりえ。森の仲間たちを一緒に楽しくぬれるよ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['しか', '動物', '森', 'ことり'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      'ことりを何色にする？',
      '落ち葉も秋らしい色でぬってみよう',
    ],
    imageUrl: '/materials/deer-normal-1-illust.png',
    illustUrl: '/materials/deer-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'deer-rich-1',
    title: 'しかのおやこと川の風景',
    description: 'しかの親子が川のそばに立つ豊かな森の風景のぬりえ。木や花、川もじっくり楽しめるよ。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['しか', '動物', '親子', '森', 'やりがい'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '川の水も青や水色でぬってみよう',
      'しかの親子はどんな会話をしているかな？',
    ],
    imageUrl: '/materials/deer-rich-1-illust.png',
    illustUrl: '/materials/deer-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hippo-simple-1',
    title: 'かわいいかばさん',
    description: '正面を向いたかわいいかばのぬりえ。大きな口と丸い体がかわいいよ。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['かば', '動物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'かばを好きな色でぬってみよう',
      'かばのお口の中は何色かな？',
    ],
    imageUrl: '/materials/hippo-simple-1-illust.png',
    illustUrl: '/materials/hippo-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hippo-easy-1',
    title: 'みずべのかばさん',
    description: '水辺に立つかばの横向きのぬりえ。シンプルな水辺の背景で楽しくぬれるよ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['かば', '動物', '水辺', 'かわいい'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'かばの体はどんな色にする？',
      '水も青くぬってみよう',
    ],
    imageUrl: '/materials/hippo-easy-1-illust.png',
    illustUrl: '/materials/hippo-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hippo-normal-1',
    title: 'かわのかばさんと魚たち',
    description: '川につかるかばと魚や蓮の花のぬりえ。水の中の生き物たちを楽しんでぬれるよ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['かば', '動物', '川', '魚', '蓮'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '魚をいろんな色でぬってみよう',
      '蓮の花も色をつけてみよう',
    ],
    imageUrl: '/materials/hippo-normal-1-illust.png',
    illustUrl: '/materials/hippo-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hippo-rich-1',
    title: 'かばのおやこと川あそび',
    description: 'かばの親子が川で水あびをする賑やかな風景のぬりえ。鳥や木々も一緒に楽しめるよ。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['かば', '動物', '親子', '川', 'やりがい'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '空を飛ぶ鳥も色をつけてみよう',
      'かばの親子はどんな遊びをしているかな？',
    ],
    imageUrl: '/materials/hippo-rich-1-illust.png',
    illustUrl: '/materials/hippo-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'flamingo-simple-1',
    title: 'かわいいフラミンゴさん',
    description: '正面を向いたかわいいフラミンゴのぬりえ。長い首と細い足がおしゃれだよ。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['フラミンゴ', '鳥', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'フラミンゴをピンク色でぬってみよう',
      'フラミンゴの足は何本かな？',
    ],
    imageUrl: '/materials/flamingo-simple-1-illust.png',
    illustUrl: '/materials/flamingo-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'flamingo-easy-1',
    title: 'みずべのフラミンゴさん',
    description: '水辺で片足立ちするフラミンゴのぬりえ。シンプルな背景で楽しくぬれるよ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['フラミンゴ', '鳥', '水辺', 'かわいい'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'フラミンゴはどんな色にする？',
      '片足で立ってみよう！バランス取れるかな？',
    ],
    imageUrl: '/materials/flamingo-easy-1-illust.png',
    illustUrl: '/materials/flamingo-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'flamingo-normal-1',
    title: 'なかよしフラミンゴ',
    description: '2羽のフラミンゴが向き合って立つぬりえ。葦のある水辺の風景も楽しめるよ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['フラミンゴ', '鳥', '水辺', '葦'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '2羽のフラミンゴに違う色をつけてみよう',
      '葦も茶色や緑でぬってみよう',
    ],
    imageUrl: '/materials/flamingo-normal-1-illust.png',
    illustUrl: '/materials/flamingo-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'flamingo-rich-1',
    title: 'フラミンゴたちの湖',
    description: 'たくさんのフラミンゴが湖のほとりに集まる豊かな風景のぬりえ。木や空もじっくり楽しめるよ。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['フラミンゴ', '鳥', '湖', '群れ', 'やりがい'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      'フラミンゴを何羽見つけられるか数えてみよう',
      '空や湖もきれいな色でぬってみよう',
    ],
    imageUrl: '/materials/flamingo-rich-1-illust.png',
    illustUrl: '/materials/flamingo-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'tiger-simple-1',
    title: 'かわいいとらさん',
    description: '正面を向いたかわいいとらのぬりえ。シマシマ模様が特徴的で、大きな線でぬりやすいよ。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['とら', '動物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'とらのシマシマを好きな色でぬってみよう',
      'とらに名前をつけてあげよう',
    ],
    imageUrl: '/materials/tiger-simple-1-illust.png',
    illustUrl: '/materials/tiger-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'tiger-easy-1',
    title: 'お花畑のとらさん',
    description: '草原でお花のそばにすわっているとらのぬりえ。シマシマ模様や花も楽しんでぬれるよ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['とら', '動物', 'お花', 'かわいい'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'とらのシマシマを何色にする？',
      'お花もいろんな色でぬってみよう',
    ],
    imageUrl: '/materials/tiger-easy-1-illust.png',
    illustUrl: '/materials/tiger-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'tiger-normal-1',
    title: 'ジャングルのとらさん',
    description: '草むらや木の葉の中に立つとらのぬりえ。シマシマ模様と背景の植物を楽しんでぬれるよ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['とら', '動物', 'ジャングル', '植物'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      'ジャングルの葉っぱも緑でぬってみよう',
      'とらはどんな表情かな？観察しながらぬろう',
    ],
    imageUrl: '/materials/tiger-normal-1-illust.png',
    illustUrl: '/materials/tiger-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'tiger-rich-1',
    title: 'とらさんのいる風景',
    description: '岩の上に座るとらと豊かな背景のぬりえ。細かいシマシマ模様や自然の描写をじっくり楽しめるよ。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['とら', '動物', '風景', 'やりがい'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      'シマシマの本数を数えてみよう',
      'とらが住んでいる場所のお話を作ろう',
    ],
    imageUrl: '/materials/tiger-rich-1-illust.png',
    illustUrl: '/materials/tiger-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'wolf-simple-1',
    title: 'かわいいおおかみさん',
    description: '正面を向いたかわいいおおかみのぬりえ。ふわふわの毛並みと大きな目がかわいいよ。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['おおかみ', '動物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'おおかみを好きな色でぬってみよう',
      'おおかみの毛はふわふわかな？',
    ],
    imageUrl: '/materials/wolf-simple-1-illust.png',
    illustUrl: '/materials/wolf-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'wolf-easy-1',
    title: 'とおぼえするおおかみさん',
    description: '草原で空に向かって遠吠えするおおかみのぬりえ。草や花もシンプルで楽しくぬれるよ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['おおかみ', '動物', '草原', 'かわいい'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'おおかみはどんな声で鳴くかな？マネしてみよう',
      'お花も色をつけてみよう',
    ],
    imageUrl: '/materials/wolf-easy-1-illust.png',
    illustUrl: '/materials/wolf-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'wolf-normal-1',
    title: 'もりをあるくおおかみさん',
    description: '森の木々の間を歩くおおかみのぬりえ。針葉樹や広葉樹も一緒に楽しんでぬれるよ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['おおかみ', '動物', '森', '木'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '木の葉っぱも緑でぬってみよう',
      '森にはどんな動物が住んでいるかな？',
    ],
    imageUrl: '/materials/wolf-normal-1-illust.png',
    illustUrl: '/materials/wolf-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'wolf-rich-1',
    title: 'おおかみのおやこと星空',
    description: 'おおかみの親子が雪山のふもとで星空を見上げる豊かな風景のぬりえ。星や月も楽しめるよ。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['おおかみ', '動物', '親子', '星空', 'やりがい'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '星をいくつ見つけられるか数えてみよう',
      '夜空を濃い青でぬってみよう',
    ],
    imageUrl: '/materials/wolf-rich-1-illust.png',
    illustUrl: '/materials/wolf-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'dolphin-simple-1',
    title: 'かわいいイルカ',
    description: 'イルカ1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['イルカ', '海の生き物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'イルカの色を自由に塗ってみよう',
      'イルカのおなかに模様を描いてみよう',
    ],
    imageUrl: '/materials/dolphin-simple-1-illust.png',
    illustUrl: '/materials/dolphin-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'dolphin-easy-1',
    title: 'イルカのジャンプ',
    description: 'イルカが海からジャンプする場面のぬりえ。水しぶきもかわいい。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['イルカ', '海の生き物', 'ジャンプ', '波'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      '海を青く塗ってみよう',
      '水しぶきを白くぬり残してみよう',
    ],
    imageUrl: '/materials/dolphin-easy-1-illust.png',
    illustUrl: '/materials/dolphin-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'dolphin-normal-1',
    title: 'イルカと魚のなかまたち',
    description: '2匹のイルカと小魚が泳ぐ水中シーン。泡や魚も塗れる楽しい構図。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 15,
    category: 'coloring', theme: 'sea',
    tags: ['イルカ', '海の生き物', '魚', '泡', '水中'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '泡を水色に塗ってみよう',
      '小魚に違う色をつけてみよう',
    ],
    imageUrl: '/materials/dolphin-normal-1-illust.png',
    illustUrl: '/materials/dolphin-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'dolphin-rich-1',
    title: 'イルカたちのにじいろサンセット',
    description: '3匹のイルカが太陽と雲の前でジャンプする賑やかなぬりえ。空・海・波の色分けが楽しめる。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 25,
    category: 'coloring', theme: 'sea',
    tags: ['イルカ', '海の生き物', '夕日', '雲', '波', 'にぎやか'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '夕焼け空をオレンジとピンクで塗ってみよう',
      '3匹のイルカにそれぞれ違う色をつけてみよう',
    ],
    imageUrl: '/materials/dolphin-rich-1-illust.png',
    illustUrl: '/materials/dolphin-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'seal-simple-1',
    title: 'かわいいアザラシ',
    description: 'アザラシ1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['アザラシ', '海の生き物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'アザラシを好きな色で塗ってみよう',
      'おめめをかわいく色付けしてみよう',
    ],
    imageUrl: '/materials/seal-simple-1-illust.png',
    illustUrl: '/materials/seal-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'seal-easy-1',
    title: 'アザラシと氷のうえ',
    description: 'アザラシが氷の上に寝そべるぬりえ。氷と海の色分けが楽しめる。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['アザラシ', '海の生き物', '氷', '波'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      '氷を水色や白でぬってみよう',
      '海の波を青く塗ってみよう',
    ],
    imageUrl: '/materials/seal-easy-1-illust.png',
    illustUrl: '/materials/seal-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'seal-normal-1',
    title: 'アザラシの親子',
    description: 'アザラシの親子が氷の上でくつろぐぬりえ。山や鳥も描かれた北極の風景。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 15,
    category: 'coloring', theme: 'sea',
    tags: ['アザラシ', '海の生き物', '親子', '氷山', '北極'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '空を薄い青でぬってみよう',
      '親と子で色を変えてみよう',
    ],
    imageUrl: '/materials/seal-normal-1-illust.png',
    illustUrl: '/materials/seal-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'seal-rich-1',
    title: 'アザラシと海のなかまたち',
    description: 'アザラシが魚・海藻・ヒトデと一緒に泳ぐ水中シーン。たくさんの生き物で色分けが楽しい。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 25,
    category: 'coloring', theme: 'sea',
    tags: ['アザラシ', '海の生き物', '魚', '海藻', 'ヒトデ', '水中'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      'それぞれの魚に違う色をつけてみよう',
      '海藻を緑に、泡を水色に塗ってみよう',
    ],
    imageUrl: '/materials/seal-rich-1-illust.png',
    illustUrl: '/materials/seal-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'otter-simple-1',
    title: 'かわいいラッコ',
    description: 'ラッコ1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['ラッコ', '海の生き物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'ラッコを好きな色で塗ってみよう',
      'おなかをふわふわに見えるよう白く塗ってみよう',
    ],
    imageUrl: '/materials/otter-simple-1-illust.png',
    illustUrl: '/materials/otter-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'otter-easy-1',
    title: 'ラッコと貝がら',
    description: 'ラッコが水に浮きながら貝がらを持っているぬりえ。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['ラッコ', '海の生き物', '貝', '海面'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      '貝がらに模様を描いてみよう',
      '海の水をきれいな水色に塗ってみよう',
    ],
    imageUrl: '/materials/otter-easy-1-illust.png',
    illustUrl: '/materials/otter-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'otter-normal-1',
    title: 'ラッコのてつなぎ',
    description: '2匹のラッコが海に浮かびながら手をつないでいるぬりえ。泡と波が広がる。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 15,
    category: 'coloring', theme: 'sea',
    tags: ['ラッコ', '海の生き物', '手つなぎ', '波', '泡'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '2匹に違う色をつけてみよう',
      '泡を水色や白で塗ってみよう',
    ],
    imageUrl: '/materials/otter-normal-1-illust.png',
    illustUrl: '/materials/otter-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'otter-rich-1',
    title: 'ラッコとうみのなかまたち',
    description: 'ラッコの親子が魚・海藻・ヒトデ・貝殻と一緒に泳ぐにぎやかな水中シーン。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 25,
    category: 'coloring', theme: 'sea',
    tags: ['ラッコ', '海の生き物', '親子', '魚', '海藻', 'ヒトデ'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '海藻を緑、泡を水色で塗ってみよう',
      'それぞれの魚に違う色をつけてみよう',
    ],
    imageUrl: '/materials/otter-rich-1-illust.png',
    illustUrl: '/materials/otter-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'jellyfish-simple-1',
    title: 'かわいいクラゲ',
    description: 'クラゲ1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['クラゲ', '海の生き物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'クラゲを好きな色で塗ってみよう',
      '触手をにじいろに塗ってみよう',
    ],
    imageUrl: '/materials/jellyfish-simple-1-illust.png',
    illustUrl: '/materials/jellyfish-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'jellyfish-easy-1',
    title: 'クラゲと海藻',
    description: 'クラゲが海藻のそばをふわふわ漂うぬりえ。泡もかわいい。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['クラゲ', '海の生き物', '海藻', '泡'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      '海藻を緑に塗ってみよう',
      'クラゲを好きな色でふわふわに塗ってみよう',
    ],
    imageUrl: '/materials/jellyfish-easy-1-illust.png',
    illustUrl: '/materials/jellyfish-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'jellyfish-normal-1',
    title: 'クラゲたちのダンス',
    description: '4匹のクラゲが魚や泡と一緒に泳ぐにぎやかな水中シーン。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 15,
    category: 'coloring', theme: 'sea',
    tags: ['クラゲ', '海の生き物', '魚', '泡', '水中'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '4匹のクラゲにそれぞれ違う色をつけてみよう',
      '泡を水色や白で塗ってみよう',
    ],
    imageUrl: '/materials/jellyfish-normal-1-illust.png',
    illustUrl: '/materials/jellyfish-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'jellyfish-rich-1',
    title: 'クラゲとうみのなかまたち',
    description: '5匹のクラゲが魚・ヒトデ・珊瑚・海藻と一緒に広がる華やかな水中シーン。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 25,
    category: 'coloring', theme: 'sea',
    tags: ['クラゲ', '海の生き物', '魚', 'ヒトデ', '珊瑚', '海藻'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      'クラゲを虹色のグラデーションで塗ってみよう',
      '珊瑚をオレンジ、海藻を緑で塗ってみよう',
    ],
    imageUrl: '/materials/jellyfish-rich-1-illust.png',
    illustUrl: '/materials/jellyfish-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'shark-simple-1',
    title: 'かわいいサメ',
    description: 'サメ1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['サメ', '海の生き物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'サメを好きな色で塗ってみよう',
      'おなかを白く塗り分けてみよう',
    ],
    imageUrl: '/materials/shark-simple-1-illust.png',
    illustUrl: '/materials/shark-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'shark-easy-1',
    title: 'サメと海の中',
    description: 'サメが海藻や珊瑚のそばを泳ぐぬりえ。泡もかわいい。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['サメ', '海の生き物', '海藻', '珊瑚', '泡'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      '海藻を緑、珊瑚をオレンジに塗ってみよう',
      'サメの背中を濃い色で塗り分けてみよう',
    ],
    imageUrl: '/materials/shark-easy-1-illust.png',
    illustUrl: '/materials/shark-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'shark-normal-1',
    title: 'サメの親子',
    description: 'サメの親子が小魚や泡と一緒に泳ぐぬりえ。大きさの違いが楽しい。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 15,
    category: 'coloring', theme: 'sea',
    tags: ['サメ', '海の生き物', '親子', '魚', '泡'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      '親と子で色を変えて塗ってみよう',
      '小魚をカラフルに塗ってみよう',
    ],
    imageUrl: '/materials/shark-normal-1-illust.png',
    illustUrl: '/materials/shark-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'shark-rich-1',
    title: 'サメたちの大海原',
    description: '5匹のサメが魚・ヒトデ・海藻・珊瑚と一緒に泳ぐにぎやかな水中シーン。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 25,
    category: 'coloring', theme: 'sea',
    tags: ['サメ', '海の生き物', '魚', 'ヒトデ', '海藻', '珊瑚'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '5匹のサメにそれぞれ違う色をつけてみよう',
      '海の底の岩や珊瑚もカラフルに塗ってみよう',
    ],
    imageUrl: '/materials/shark-rich-1-illust.png',
    illustUrl: '/materials/shark-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hermit-crab-simple-1',
    title: 'かわいいヤドカリ',
    description: 'ヤドカリ1匹のシンプルなぬりえ。2〜3歳向けの大きな輪郭線。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['ヤドカリ', '海の生き物', 'かわいい', 'シンプル'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      'ヤドカリの貝がらを好きな色で塗ってみよう',
      'はさみをオレンジや赤で塗ってみよう',
    ],
    imageUrl: '/materials/hermit-crab-simple-1-illust.png',
    illustUrl: '/materials/hermit-crab-simple-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hermit-crab-easy-1',
    title: 'ヤドカリのさんぽ',
    description: 'ヤドカリが砂浜を歩くぬりえ。貝殻も一緒に描かれている。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 10,
    category: 'coloring', theme: 'sea',
    tags: ['ヤドカリ', '海の生き物', '砂浜', '貝殻'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: [
      '貝がらに縞模様を描いて塗ってみよう',
      '砂浜を薄い黄色で塗ってみよう',
    ],
    imageUrl: '/materials/hermit-crab-easy-1-illust.png',
    illustUrl: '/materials/hermit-crab-easy-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hermit-crab-normal-1',
    title: 'ヤドカリとうみのたから',
    description: 'ヤドカリがヒトデ・貝殻・石と一緒にいる海辺のぬりえ。',
    ageMin: 3, ageMax: 5, difficulty: 3, duration: 15,
    category: 'coloring', theme: 'sea',
    tags: ['ヤドカリ', '海の生き物', 'ヒトデ', '貝殻', '石'],
    tools: ['色えんぴつ', 'クレヨン'],
    activityIdeas: [
      'ヒトデをオレンジや赤で塗ってみよう',
      '貝殻にそれぞれ違う模様をつけてみよう',
    ],
    imageUrl: '/materials/hermit-crab-normal-1-illust.png',
    illustUrl: '/materials/hermit-crab-normal-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
  {
    id: 'hermit-crab-rich-1',
    title: 'ヤドカリたちの海の世界',
    description: '4匹のヤドカリが魚・珊瑚・海藻・ヒトデと一緒に泳ぐにぎやかな水中シーン。',
    ageMin: 4, ageMax: 6, difficulty: 4, duration: 25,
    category: 'coloring', theme: 'sea',
    tags: ['ヤドカリ', '海の生き物', '魚', '珊瑚', '海藻', 'ヒトデ'],
    tools: ['色えんぴつ', '細筆'],
    activityIdeas: [
      '4匹の貝がらにそれぞれ違う色・模様をつけてみよう',
      '珊瑚をピンクやオレンジで塗ってみよう',
    ],
    imageUrl: '/materials/hermit-crab-rich-1-illust.png',
    illustUrl: '/materials/hermit-crab-rich-1-illust.png',
    illustVersion: 1,
    imageStatus: 'pending_review',
    pdfUrl: '',
    createdAt: '2026-05-11',
    popular: false,
  },
{
    id: 'ostrich-simple-1',
    title: 'かわいいダチョウ',
    description: 'シンプルなダチョウのぬりえ。大きな体と長い首が特徴的です。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['ダチョウ', '動物', 'アフリカ', 'とり', '鳥'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: ['ダチョウの体の色を観察してみよう', '世界一大きな鳥だよ'],
    imageUrl: '/materials/ostrich-simple-1-illust.png',
    illustUrl: '/materials/ostrich-simple-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
  {
    id: 'ostrich-easy-1',
    title: 'ダチョウ',
    description: '草原に立つダチョウのぬりえ。長い脚と首をぬりましょう。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['ダチョウ', '動物', 'アフリカ', 'とり', '鳥', '草原'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: ['茶色と黒の羽を塗ってみよう', '卵は大きいよ'],
    imageUrl: '/materials/ostrich-easy-1-illust.png',
    illustUrl: '/materials/ostrich-easy-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
  {
    id: 'ostrich-normal-1',
    title: 'ダチョウの親子',
    description: '親子のダチョウが草原にいる場面のぬりえです。',
    ageMin: 4, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['ダチョウ', '動物', 'アフリカ', '親子', '草原'],
    tools: ['色えんぴつ', 'マーカー'],
    activityIdeas: ['親と子どもの大きさを比べよう', '草の色も工夫してみよう'],
    imageUrl: '/materials/ostrich-normal-1-illust.png',
    illustUrl: '/materials/ostrich-normal-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
  {
    id: 'ostrich-rich-1',
    title: 'ダチョウの群れ',
    description: 'サバンナを歩くダチョウの群れ。木や太陽も一緒にぬりましょう。',
    ageMin: 5, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['ダチョウ', '動物', 'アフリカ', 'サバンナ', '群れ'],
    tools: ['色えんぴつ', 'マーカー', '水彩'],
    activityIdeas: ['群れでどんな生活をしているか調べよう', 'サバンナの風景を作ろう'],
    imageUrl: '/materials/ostrich-rich-1-illust.png',
    illustUrl: '/materials/ostrich-rich-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },

  {
    id: 'peacock-simple-1',
    title: 'かわいいクジャク',
    description: 'きれいな羽を広げたクジャクのぬりえ。丸い模様をぬりましょう。',
    ageMin: 2, ageMax: 3, difficulty: 1, duration: 10,
    category: 'coloring', theme: 'animals',
    tags: ['クジャク', '動物', 'とり', '鳥', '羽'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: ['きれいな色で羽をぬってみよう', '丸い模様を数えてみよう'],
    imageUrl: '/materials/peacock-simple-1-illust.png',
    illustUrl: '/materials/peacock-simple-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
  {
    id: 'peacock-easy-1',
    title: 'クジャク',
    description: '草原に立つクジャクのぬりえ。大きな尾羽が見事です。',
    ageMin: 3, ageMax: 4, difficulty: 2, duration: 15,
    category: 'coloring', theme: 'animals',
    tags: ['クジャク', '動物', 'とり', '鳥', '羽', '草原'],
    tools: ['クレヨン', '色えんぴつ'],
    activityIdeas: ['青や緑でカラフルにぬろう', '羽の模様に挑戦しよう'],
    imageUrl: '/materials/peacock-easy-1-illust.png',
    illustUrl: '/materials/peacock-easy-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
  {
    id: 'peacock-normal-1',
    title: 'クジャクの親子',
    description: '親クジャクとひなが花畑にいるぬりえです。',
    ageMin: 4, ageMax: 5, difficulty: 3, duration: 20,
    category: 'coloring', theme: 'animals',
    tags: ['クジャク', '動物', '親子', 'とり', '鳥', '花'],
    tools: ['色えんぴつ', 'マーカー'],
    activityIdeas: ['親と子の違いを観察しよう', '花もカラフルに塗ってみよう'],
    imageUrl: '/materials/peacock-normal-1-illust.png',
    illustUrl: '/materials/peacock-normal-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
  {
    id: 'peacock-rich-1',
    title: 'クジャクと花園',
    description: '花やちょうちょと一緒のクジャクのぬりえ。にぎやかな場面です。',
    ageMin: 5, ageMax: 6, difficulty: 4, duration: 30,
    category: 'coloring', theme: 'animals',
    tags: ['クジャク', '動物', 'とり', '鳥', '花', 'チョウ', '自然'],
    tools: ['色えんぴつ', 'マーカー', '水彩'],
    activityIdeas: ['花の色を自由に決めよう', '背景の木も緑に塗ろう'],
    imageUrl: '/materials/peacock-rich-1-illust.png',
    illustUrl: '/materials/peacock-rich-1-illust.png',
    illustVersion: 1, imageStatus: 'pending_review',
    pdfUrl: '', createdAt: '2026-05-11', popular: false,
  },
]

export type SortKey = 'newest' | 'popular' | 'favorites'

// フィルタリング関数
export function filterMaterials(params: {
  age?: number
  category?: string
  season?: string
  event?: string
  theme?: string
  difficulty?: number
  search?: string
  sort?: SortKey
  favoriteIds?: string[]
}): Material[] {
  const filtered = materials.filter(m => {
    if (params.age && (m.ageMin > params.age || m.ageMax < params.age)) return false
    if (params.category && m.category !== params.category) return false
    if (params.season && m.season !== params.season) return false
    if (params.event && m.event !== params.event) return false
    if (params.theme && m.theme !== params.theme) return false
    if (params.difficulty && m.difficulty !== params.difficulty) return false
    if (params.search) {
      const q = normalizeQuery(params.search)
      const haystack = normalizeText([m.title, m.description, ...m.tags].join(' '))
      if (!haystack.includes(q)) return false
    }
    return true
  })

  const sort = params.sort ?? 'newest'

  if (sort === 'popular') {
    return [...filtered].sort((a, b) => {
      if (a.popular !== b.popular) return a.popular ? -1 : 1
      const da = b.downloadCount ?? 0
      const db = a.downloadCount ?? 0
      if (da !== db) return da - db
      return b.createdAt.localeCompare(a.createdAt)
    })
  }

  if (sort === 'favorites' && params.favoriteIds) {
    const favSet = new Set(params.favoriteIds)
    return [...filtered].sort((a, b) => {
      const af = favSet.has(a.id) ? 1 : 0
      const bf = favSet.has(b.id) ? 1 : 0
      if (af !== bf) return bf - af
      return b.createdAt.localeCompare(a.createdAt)
    })
  }

  // newest（デフォルト）
  return [...filtered].sort((a, b) => b.createdAt.localeCompare(a.createdAt))
}

export function getPopularMaterials(limit = 6): Material[] {
  return materials.filter(m => m.popular).slice(0, limit)
}

export function getMaterialById(id: string): Material | undefined {
  return materials.find(m => m.id === id)
}

export function getRelatedMaterials(material: Material, limit = 4): Material[] {
  return materials
    .filter(m => m.id !== material.id && (
      m.category === material.category ||
      m.theme === material.theme ||
      m.event === material.event
    ))
    .slice(0, limit)
}
